# DOWNLOAD STOCK MARKET DATA AND ANALYSING IT

### Extracting Stock Data from Yahoo Finance

In [ ]:
#Importing the Yahoo Finance Library
import yfinance as yf

#To extract the stock data of the HDFC Bank between '2021-10-19' and end='2022-10-19'

#NSE symbol for HDFC bank
symbol = "HDFCBANK.NS"

#Creating a ticker object
tickerData = yf.Ticker(symbol)

#get the historical prices for this ticker (perid='1d' implies daily data)
tickerDf = tickerData.history(period='1d', start='2021-10-19', end='2022-10-19')

In [ ]:
#The extracted data in a data frame
tickerDf

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-10-19 00:00:00+05:30,1656.193303,1672.997915,1651.794497,1669.291016,4493770,0.0,0
2021-10-20 00:00:00+05:30,1669.686543,1679.225656,1645.319830,1654.611816,5454284,0.0,0
2021-10-21 00:00:00+05:30,1652.585412,1662.618657,1641.761192,1657.033691,4869095,0.0,0
2021-10-22 00:00:00+05:30,1660.789942,1688.369300,1651.547429,1661.432495,6087777,0.0,0
2021-10-25 00:00:00+05:30,1670.576162,1670.576162,1595.252007,1637.955444,8213383,0.0,0
...,...,...,...,...,...,...,...
2022-10-12 00:00:00+05:30,1403.199951,1414.849976,1397.300049,1409.800049,4612525,0.0,0
2022-10-13 00:00:00+05:30,1402.050049,1406.250000,1384.000000,1393.599976,7357117,0.0,0
2022-10-14 00:00:00+05:30,1417.000000,1447.000000,1415.250000,1439.000000,6424960,0.0,0
2022-10-17 00:00:00+05:30,1435.000000,1457.599976,1427.000000,1446.550049,9205250,0.0,0
2022-10-18 00:00:00+05:30,1458.050049,1462.900024,1440.000000,1443.849976,5280554,0.0,0

## Exercise

**Question 1:**

Design a function named 
        
           get_stock_data(symbol, start_date, end_date)

that would take a stock symbol, a start date and an end date and generate a data frame of the above kind.

For example,

            get_stock_data('TATAMOTORS.NS', start_date='2021-10-19', end_date='2022-10-19').head() 

Would return...

                              Open	      High	      Low	     Close	 Volume	   Dividends	Stock Splits
            Date							
            2021-10-19	512.450012	517.400024	476.049988	481.899994	57428637	0	         0
            2021-10-20	481.799988	497.000000	471.250000	486.899994	55444814	0	         0
            2021-10-21	491.750000	510.399994	485.750000	508.000000	52608672	0	         0
            2021-10-22	509.899994	510.700012	487.399994	490.899994	42742785	0	         0
            2021-10-25	493.899994	496.000000	473.250000	479.899994	33107841	0	         0

In [ ]:
#importing yfinance libray
import yfinance as yf

#defining the get_stock_data function
def get_stock_data(symbol, start_date, end_date):  
    
    #reading the ticker data using the Ticker function by passing the symbol from parameters
    tickerData = yf.Ticker(symbol)
    
    #get the data using the history function
    tickerDf = tickerData.history(period='1d', start=start_date, end=end_date)
    
    #convert the date format to YYYY-MM-DD
    tickerDf.index = tickerDf.index.strftime('%Y-%m-%d')
    
    #return the data frame
    return tickerDf

In [ ]:
get_stock_data('TATAMOTORS.NS', start_date='2021-10-19', end_date='2022-10-19').head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-10-19,512.450012,517.400024,476.049988,481.899994,57428637,0,0
2021-10-20,481.799988,497.000000,471.250000,486.899994,55444814,0,0
2021-10-21,491.750000,510.399994,485.750000,508.000000,52608672,0,0
2021-10-22,509.899994,510.700012,487.399994,490.899994,42742785,0,0
2021-10-25,493.899994,496.000000,473.250000,479.899994,33107841,0,0

**Question 2**

Create a function named

        export_stock_data(symbol, start_date, end_date, directory)
        
that would take a stock symbol, a start date, an end date and a path (directory) to generate a data frame of the above kind and export it as a CSV file in the given directory with the name of the file as the symbol of the stock.

In [ ]:
#importing yfinance libray
import yfinance as yf
import os

#defining the get_stock_data function
def export_stock_data(symbol, start_date, end_date,directory):  
    
    #reading the ticker data using the Ticker function by passing the symbol from parameters
    tickerData = yf.Ticker(symbol)
    
    #get the data using the history function
    tickerDf = tickerData.history(period='1d', start=start_date, end=end_date)
    
    #convert the date format to YYYY-MM-DD
    tickerDf.index = tickerDf.index.strftime('%Y-%m-%d')
    
    #converting the backslashes to forward slashes
    #directory = directory.replace('/','\\')
    
    #keep the current working directory.
    currDir = os.getcwd()
    
    #saving the file to a CSV file with symbol as name
    os.chdir(directory)
    tickerDf.to_csv(symbol+".csv")
    
    #change back to the python directory for future codes
    os.chdir(currDir)
    
    #return the data frame
    return tickerDf

In [ ]:
export_stock_data('TATAMOTORS.NS', start_date='2021-10-19', end_date='2022-10-19',directory= r'C:\Users\asus\Downloads\py exam')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-10-19,512.450012,517.400024,476.049988,481.899994,57428637,0,0
2021-10-20,481.799988,497.000000,471.250000,486.899994,55444814,0,0
2021-10-21,491.750000,510.399994,485.750000,508.000000,52608672,0,0
2021-10-22,509.899994,510.700012,487.399994,490.899994,42742785,0,0
2021-10-25,493.899994,496.000000,473.250000,479.899994,33107841,0,0
...,...,...,...,...,...,...,...
2022-10-12,394.549988,398.200012,391.100006,396.549988,14287344,0,0
2022-10-13,396.549988,403.500000,394.549988,399.000000,12584114,0,0
2022-10-14,407.000000,409.200012,395.299988,396.250000,12875470,0,0
2022-10-17,394.000000,398.899994,392.500000,396.100006,9543556,0,0
2022-10-18,401.000000,406.700012,400.700012,404.250000,14215544,0,0

**Question 3**

The file nifty50.csv contains the name and symbols of all the 50 stocks of nifty-50.

Use the function named

        export_stock_data(symbol, start_date, end_date, directory)
        
that would take the stock symbol one at a time from the nifty50.csv file to generate a data frame of the above kind and export it as a CSV file inside a NEW FOLDER in the given directory with the name of the file as exactly equal to the symbol of the stock given in the CSV file.

**Note:**

1. The symbols given in the dataset do not have the suffix .NS which needs to be added to the symbols before it can be used in the function.

2. The new folder must be created with the name NIFTY50

3. All the data frames must be exported as a CSV files as saved in the NIFTY50 folder

In [ ]:
import pandas as pd

nifty50 = pd.read_csv('nifty50.csv')

#keep the parent directory for future use
parentdict = os.getcwd()

#change the directory to the NEW FOLDER
os.chdir(os.getcwd())

#create the new folder called NIFTY 50
os.mkdir('NIFTY50')

#Use the new folder created to save the 
os.chdir(os.getcwd()+'\\NIFTY50')

#keep the directory name for each iteration
directory = os.getcwd()

#initialize the dates
start_date = '2021-10-19'
end_date = '2022-10-19' 

#Run the loop for each company in the NIFTY 50 file
for symbol in nifty50.Symbol:
    
    #add .NS to the symbol name
    symbol = symbol+".NS"
    
    #call the export function to save each file
    export_stock_data(symbol, start_date, end_date, directory)

**Question 4**

Create a function called,

    daily_return(df)
    
This function should be able to take a dataframe shown in the example above and calculate the daily return of the close price and output a dataframe with the same number of columns and an additional column named "**Return_Close**". 

The daily return for a day is calculated as follows:

    daily return = (today's price - previous day's price)/(previous day's price)*100

**Note:** You can calculate the daily return starting from the day 2. The return for the day 1 should be set to 0.

In [ ]:
#get the dataframe using the function get_stock_data
df = get_stock_data('TATAMOTORS.NS', start_date='2021-10-19', end_date='2022-10-19')

#defining the daily_return function
def daily_return(df):
    
    #creating an empty list to hold the daily return values
    daily_return =[]    
    
    #running for loop for each day in the dataframe
    for i in range(len(df)):
        
        #for first row we have to save zero as daily return
        #from the second row onwards we use the equation :
        #daily return = (today's price - previous day's price)/(previous day's price)*100
        
        #drValue = daily return variable to hold each day's data
        
        if (i == 0):
            drValue = 0
        else:
            drValue = (df.Close[i] - df.Close[i-1])*100/df.Close[i-1]
            
        #saving each daily return value to the list
        daily_return.append(drValue)
        
    #Create the new column Return_Close and use the daily return values list we created for the data
    df['Return_Close'] = daily_return
    
    #return the new dataframe
    return df

**Question 5**

Consider the NIFTY50 folder created in Q3. This folder should contain 50 data frames - one for each stocks in the Nifty-50 list. Create a function called,

    get_return(directory)
    

This function would take the link to the NIFTY50 folder, read one CSV file at a time present inside it, calulate the return of the close price, save the return value in an new column called "Return" and update the CSV file.

In [ ]:
## Reading code taken partially from https://www.geeksforgeeks.org/how-to-read-all-csv-files-in-a-folder-in-pandas/
# import necessary libraries
import pandas as pd
import os
import glob
  
#use glob to get all the csv files
path = os.getcwd()
csv_files = glob.glob(os.path.join(path, "*.csv"))
  
def get_return(directory):
    
    # loop through all the files
    for file in csv_files:

        # read the csv file
        df = pd.read_csv(file)
        
        #use the daily_return function to calculate and create the column for return of the close price 
        df = daily_return(df)
        
        #renaming the Return_Close to Return
        
        df.rename(columns = {'Return_Close':'Return'}, inplace = True)
        #export the updated csv file to the same folder
        df.to_csv(file, index=False)
        
get_return(os.getcwd())

**Question 6**

Modify the get_return() function such that it has another argument,

    get_return(directory, plot = False)
    
If the argument plot is set to False the the output of this function is same as the function in Q6. However, if it is set to True then for every stock we get a line plot in the JPEG format exported in a separate folder named **Graphs** inside the parent directory.

In [ ]:
## Reading csv code taken partially from https://www.geeksforgeeks.org/how-to-read-all-csv-files-in-a-folder-in-pandas/
# import necessary libraries
import pandas as pd
import os
import glob
import matplotlib.pyplot as plt
import seaborn as sns
  
#use glob to get all the csv files
path = os.getcwd()
csv_files = glob.glob(os.path.join(path, "*.csv"))

#Creating the Graphs folder
os.chdir(parentdict)
os.mkdir('Graphs')

#Changin back to NIFTY50 Folder to process the files
os.chdir(parentdict+"\\NIFTY50")

#define the function
def get_return(directory, plot):
    
    # loop through all the files
    for file in csv_files:

        # read the csv file
        df = pd.read_csv(file)
        
        #use the daily_return function to calculate and create the column for return of the close price 
        df = daily_return(df)
        
        #renaming the Return_Close to Return
        
        df.rename(columns = {'Return_Close':'Return'}, inplace = True)
        #export the updated csv file to the same folder
        df.to_csv(file, index=False)
        
        #if the plot is True we have to save the linegraphs in Graphs folder
        if plot : 
            
            #go to Graphs Folder
            os.chdir(parentdict+"\\Graphs")
            
            #plot the line graph using seaborn lineplot function
            sns.lineplot( data = df)
            
            #labelling graph
            plt.xlabel('Dates')
            plt.ylabel('Prices')
            plt.title("Graph for "+file[file.rfind('\\')+1:-4])
            
            #saving the figure with nomenclature:  company_name.jpeg
            plt.savefig(file[file.rfind('\\')+1:-4] + ".jpeg")
            
            #to avoid the cumulative graphs we clear after each iteration
            plt.clf()
            
            #after each saving graph, go back to NIFTY 50 folder to read the next file
            os.chdir(parentdict+"\\NIFTY50")
        
get_return(os.getcwd(), True)